- 👋 Hi, I’m @NoobProgrammer004
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
NoobProgrammer004/NoobProgrammer004 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
a=input(input("Enter any number"))
print(a)
